#+title: Transição 🏳️‍⚧️
#+author: roridev <roridev@protonmail.com>

Status Atual: ~~Pre-Transição~~.

** Pré-transição
Criação de todos os sistemas necessários para a transição do servidor.

Implementação da infraestrutura nova e dos plugins/mods de proteção do servidor.

** V1-em-V2
Fase inicial da transição onde somente a [[infra.org][Infraestrutura nova]] será utilizada, O servidor em sí continuará rodando no V1 (congelado).
** V2 Quilt
Uma atualização de todo o servidor, incluindo o proxy para a versão mais recente do minecraft (_target:_ 1.19.3)
reativando o suporte para Bedrock caso esse estiver quebrado.

- Implementação inicial do sistema de proteção será lançada globalmente.
- Migração do sistema de autenticação para o proxy e desligamento dos IPs de conexão direta com os servidores.
** V2 Purpur
Parte opcional caso o servidor continue lagando/crashando. 
O servidor será migrado para o [[https://purpurmc.org][Purpur]] (Spigot-based) e suporte para alguns mods serão dropados (EMI/ *CarpetMod*).

Mods se tornam plugins e deixam de ser obtidos pelo ~~modrinth.com | curseforge.com~~ e são obtidos pelo ~~spigotmc.org~~.

Paridade com o vanilla poderá sofrer devido aos patchs do Purpur influenciarem em algumas mecânicas do jogo.
